# Generated by Django 2.0.3 on 2018-03-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20180314_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='pavicon',
            new_name='favicon',
        ),
    ]
