# Generated by Django 2.0.3 on 2018-03-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='img',
            new_name='image',
        ),
    ]
